[project]
name = "glowbyte-jira"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "jira>=3.8.0",
    "pydantic-settings>=2.8.1",
    "python-telegram-bot[job-queue]>=22.0",
]
